server.port=8080
spring.application.name=nspace-java-backend
spring.profiles.active=docker


# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:3000,http://vue-frontend
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Security
jwt.secret=${JWT_SECRET}

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
