

services:
  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
      args:
        VITE_JAVA_API_URL: ${VITE_JAVA_API_URL}
        VITE_PYTHON_API_URL: ${VITE_PYTHON_API_URL}
    #container_name: nspace-frontend
    container_name: nspace-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      #- "3000:80"
    depends_on:
      - java-backend
      - python-backend
    networks:
      - app-network
    # environment:
     # - VITE_JAVA_API_URL=http://java-backend:8080
     # - VITE_PYTHON_API_URL=http://python-backend:8000

  java-backend:
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    container_name: nspace-java
    ports:
      - "${JAVA_PORT}:8080"
      #- "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      #- SPRING_PROFILES_ACTIVE=docker
      SERVER_PORT: ${JAVA_PORT}
      #- SERVER_PORT=8080
    networks:
      - app-network

  python-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: nspace-python
    ports:
      - "${PYTHON_PORT}:8000"
      #- "8000:8000"
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SYSTEM_PROMPT: ${SYSTEM_PROMPT}
    networks:
      - app-network

networks:
  app-network:
